version: '3.7'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - .:/server
    command: yarn start:dev
    ports:
      - '7998:7998'
    environment:
      NODE_ENV: development
      PORT: 7998
    depends_on:
      - postgres
    networks:
      - local
  postgres:
    image: postgres:12
    networks:
      - local
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: henefisa
      POSTGRES_DB: ecommerce
      POSTGRES_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
    networks:
      - local
    depends_on:
      - postgres
networks:
  local:
    driver: bridge
volumes:
  db:
